### ISSUE TITLE
Vue Auth Help Needed

### ISSUE THREAD

**Issue by abdullahonden** [creativetimofficial/ct-vue-paper-dashboard-pro#15] opened 2017-09-19 07:31 UTC
Hello Everyone,

We've been trying to build the authentication and authorization logic for our project with your admin theme but we have no luck till now, maybe its because this is our first Vue project, we thought we can get some help from you and others can get good information with this topic.

We read almost every Vue auth article and lastly we tried this library: **https://github.com/websanova/vue-auth**

We installed this package as sutiable to Axius. But none of the requests sending body information. What you think that we're missing here? The request information is exists but it doesn't have body, for example in login page it doesn't send username or password?

Maybe you can give us a tip for building a basic login and auth system for begiggners like us :)

**Comment by cristijora** [comment] 2017-09-19 08:16
Hi @abdullahonden Thanks for using the dashboard! 

Although the auth is not a part of our template, I would be glad to help with what I can.
Based on my experience with such stuff, you can either to the auth layer yourself (basically make the login requests and a small vue-router middleware to check if the token is valid) or use a plugin for that.
The plugin you pointed one is pretty much the best "technical" solution out there but their documentation from my point of view is not the best.

Depending on how your auth layer is implemented on the backend you might want to make slightly different changes to the setup I will post bellow. I will pase some code from my last project and explain it a bit. It uses `vue-auth`

```js
import Vue from 'vue'
import VueAuth from '@websanova/vue-auth'
import HttpDriver from '@websanova/vue-auth/drivers/http/axios.1.x'
import VueRouterDriver from '@websanova/vue-auth/drivers/router/vue-router.2.x'
import querystring from 'querystring'

export default function () {

    Vue.use(VueAuth, {
        parseUserData (data) {
            return data;
        },
        auth: {
            request (req, token) {
                this.options.http._setHeaders.call(this, req, {Authorization: 'Bearer ' + token});
            },

            response (res) {
                const {access_token, refresh_token, expires_in} = res.data;
                if (res.data && access_token && refresh_token && expires_in) { /*get tokens if none present then*/
                    let expires_inDate = new Date();
                    /*get exact time of expiration token*/
                    expires_inDate.setSeconds(expires_inDate.getSeconds() + expires_in)
                    localStorage.setItem('expires_in', expires_inDate)
                    localStorage.setItem('refresh_token', refresh_token)
                    return access_token;
                }
            }
        },
        http: HttpDriver,
        router: VueRouterDriver,
        loginData: {
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded'
            },
            data: querystring.stringify({
                grant_type: 'password',
            }),
            url: 'auth/token',
            rememberMe: true,
            fetchUser: true,
        },
        /*Default refresh request data and redirect.*/
        refreshData: {
            /*send refresh token before expiring to renew tokens*/
            url: 'auth/token',
            method: 'POST',
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded'
            },
            data: querystring.stringify({
                grant_type: 'refresh_token',
                refresh_token: getRefreshToken()
            }),
            enabled: true,
            interval: 0, /*0=no auto refresh*/
            /*Problem: requests new refresh token without checking the expiration date*/
            fetchUser: false,
        },
        tokenExpired() {
            const expires_in = localStorage.getItem('expires_in')
            const now = new Date();
            const isExpired = expires_in && new Date(expires_in) < now
            if(isExpired){
                Vue.auth.options.refreshData.data = querystring.stringify({
                    client_id: 'F1179B6B-15A8-4250-9ED9-4C2D5EE0376B',
                    grant_type: 'refresh_token',
                    refresh_token: getRefreshToken()
                });
            }
            return isExpired
        },
        tokenOtherName: 'access_token',
        tokenDefaultName: 'access_token',
    });
}

function getRefreshToken() {
    return localStorage.getItem('refresh_token')
}
````

This is the setup for vue-auth which pretty much overrides the auth request and the setup for refresh tokens (if you use them)

The first part
```js
auth: {
            request (req, token) {
                this.options.http._setHeaders.call(this, req, {Authorization: 'Bearer ' + token});
            },

            response (res) {
                const {access_token, refresh_token, expires_in} = res.data;
                if (res.data && access_token && refresh_token && expires_in) { /*get tokens if none present then*/
                    let expires_inDate = new Date();
                    /*get exact time of expiration token*/
                    expires_inDate.setSeconds(expires_inDate.getSeconds() + expires_in)
                    localStorage.setItem('expires_in', expires_inDate)
                    localStorage.setItem('refresh_token', refresh_token)
                    return access_token;
                }
            }
        },
```

Is responsible of seating the necessary headers. In my example, upon each request I set an `Authorization` header which starts with `Bearer`. Upon each response, if my response contains an `access_token` then I verify it's expiration time and store than in local storage. Note here that the token itself is not stored in the method because it's stored by vue-auth.

The second part of the setup is the initial login data to be sent upon `$auth.login` requests
```js
loginData: {
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded'
            },
            data: querystring.stringify({
                grant_type: 'password',
            }),
            url: 'auth/token',
            rememberMe: true,
            fetchUser: true,
        },
```
In my case, the login request is of `application/x-www-form-urlencoded` type. If it's a json request in your case you most likely don't need to set `headers` and `data here. The `url` here represents the api endpoint for your login method.

Below is the authentication method itself where you have the login form.
```js
this.$auth.login({
                            data: querystring.stringify({
                                username: this.loginModel.username,
                                password: this.loginModel.password,
                            }),
                            redirect: {name: redirect ? redirect.from.name : 'Overview'},
                            success() {
                               // treat success here
                            },
                            error(res) {
                               // treat failed login/errors here
                            }
                        });
```
Again if your api endpoint supports json you simply need 
```js
 data: {
      username: this.loginModel.username,
      password: this.loginModel.password,
},
```

Next up is the `refreshData` option which has pretty much the same logic as the `loginData`. If you need details regarding that let me know. Don't want to explain it in detail if it's not needed.

` tokenExpired()` is a method I have overriden to check whether a token is expired or not. This method is called upon navigating to each route + at predefined interval ` interval: 0, /*0=no auto refresh*/` if it's set.

The last part you have to do is to wire up `vue` and `axios`. Here is my configuration.
```js
import Vue from 'vue'
import VueAxios from 'vue-axios'
import {Message} from 'element-ui'
import * as axios from "axios";
var instance = axios.create({
    baseURL: '',
    timeout: 10000,
});
Vue.use(VueAxios, instance)

// this is optional
instance.interceptors.response.use(null, (err) => {
    if(err  && err.message){
        Message({
            showClose: true,
            message: err.message,
            type: 'error'
        })
    }

    return Promise.reject(err);
});

export default instance;
```
You would use this instance for all requests so vue-auth can know about each request. The `instance.interceptors.response.use` is a middleware to treat errors generally. Handy if for example some errors are not treated but you still want to display some messages/popups.

As a bonus, you can wrap everything in a plugin and don't worry about imports when making api requests.

Example:
```js
import axios from './config'  // This is the axios instance from above

function getState() {
    return axios.get('api/state')
}
export default {
    getState
}
```
```js
//gather all services in one file
import myService from './myService'

export default{
    myService
}
```

```js
//define a plugin
import services from './../services/index.js'

const Plugins = {
    install (Vue) {
        Vue.prototype.$api = services
    }
}

export default Plugins
```

``js
import servicePlugin from './servicePlugin'
Vue.use(servicePlugin)
```

Then you can make api requests without worrying too much about imports
```js
//in any component
this.$api.myService.getState().then((data) => //my logic)
```

The last part is totally optional and you might need or not need it. If you have a bigger team, then most likely you might not want to do this because imports will be more predictable/readable.

**Comment by abdullahonden** [comment] 2017-09-19 09:49
Thank you for the detailed answer, I believe this is going to be a tutorial for most of the new comers. But, we still have the request problem, which basically can't send body information. We are using Laravel's jwt-auth package for our backend. I think my teammate Mesut (@mvatansever) can share detailed information about the problem with some code examples or such. Really appreciated for your support!

**Comment by mvatansever** [comment] 2017-09-19 09:55
I'm working with @abdullahonden in the same project. I implement this but the same problem going here. Still, the body of the request is not sent with the request but headers are going well.

Our full main.js is below:

```
import Vue from 'vue'
import axios from 'axios';
import VueAxios from 'vue-axios';
import VueAuth from './vue-auth'
import VueRouter from 'vue-router'
import VueNotify from 'vue-notifyjs'
import VeeValidate from 'vee-validate'
import lang from 'element-ui/lib/locale/lang/en'
import locale from 'element-ui/lib/locale'
import App from './App.vue'
// Plugins
import GlobalComponents from './gloablComponents'
import GlobalDirectives from './globalDirectives'
import SideBar from './components/UIComponents/SidebarPlugin'

// router setup
import router from './routes/routes'
Vue.router = router

// library imports

import './assets/sass/paper-dashboard.scss'
import './assets/sass/demo.scss'
import 'es6-promise/auto'

import sidebarLinks from './sidebarLinks'
// plugin setup
Vue.use(VueRouter)
Vue.use(GlobalDirectives)
Vue.use(GlobalComponents)
Vue.use(VueNotify)
Vue.use(SideBar, {sidebarLinks: sidebarLinks})
Vue.use(VeeValidate)


Vue.use(VueAxios, axios);
Vue.axios.defaults.baseURL = 'http://ourapi.dev';
Vue.use(VueAuth)

locale.use(lang)

/* eslint-disable no-new */
new Vue({
  el: '#app',
  render: h => h(App),
  auth: {
    request (req, token) {
      this.options.http._setHeaders.call(this, req, {Authorization: 'Bearer ' + token});
    },

    response (res) {
      const {access_token, refresh_token, expires_in} = res.data;
      if (res.data && access_token && refresh_token && expires_in) { /*get tokens if none present then*/
        let expires_inDate = new Date();
        /*get exact time of expiration token*/
        expires_inDate.setSeconds(expires_inDate.getSeconds() + expires_in)
        localStorage.setItem('expires_in', expires_inDate)
        localStorage.setItem('refresh_token', refresh_token)
        return access_token;
      }
    }
  },
  router
})
```

My full content of vue-auth.js which import at the main.js is below:

```
import Vue from 'vue'
import VueAuth from '@websanova/vue-auth'
import HttpDriver from '@websanova/vue-auth/drivers/http/axios.1.x'
import VueRouterDriver from '@websanova/vue-auth/drivers/router/vue-router.2.x'
import querystring from 'querystring'

export default function () {

    Vue.use(VueAuth, {
        parseUserData (data) {
            return data;
        },
        auth: {
            request (req, token) {
                this.options.http._setHeaders.call(this, req, {Authorization: 'Bearer ' + token});
            },

            response (res) {
                const {access_token, refresh_token, expires_in} = res.data;
                if (res.data && access_token && refresh_token && expires_in) { /*get tokens if none present then*/
                    let expires_inDate = new Date();
                    /*get exact time of expiration token*/
                    expires_inDate.setSeconds(expires_inDate.getSeconds() + expires_in)
                    localStorage.setItem('expires_in', expires_inDate)
                    localStorage.setItem('refresh_token', refresh_token)
                    return access_token;
                }
            }
        },
        http: HttpDriver,
        router: VueRouterDriver,
        loginData: {
            headers: {
                'Content-Type': 'application/json',
            },
            url: 'auth/token',
        },
        /*Default refresh request data and redirect.*/
        refreshData: {
            /*send refresh token before expiring to renew tokens*/
            url: 'auth/refresh',
            method: 'POST',
            enabled: true,
            interval: 0, /*0=no auto refresh*/
            /*Problem: requests new refresh token without checking the expiration date*/
            fetchUser: false,
        },
        tokenExpired() {
            const expires_in = localStorage.getItem('expires_in')
            const now = new Date();
            const isExpired = expires_in && new Date(expires_in) < now
            if(isExpired){
                Vue.auth.options.refreshData.data = querystring.stringify({
                    refresh_token: getRefreshToken()
                });
            }
            return isExpired
        },
        tokenDefaultName: 'access_token',
    });
}

function getRefreshToken() {
    return localStorage.getItem('refresh_token')
}
```

**Comment by cristijora** [comment] 2017-09-19 10:08
Alright. This `auth` part here is not necessary
```js
new Vue({
  el: '#app',
  render: h => h(App),
  auth: {
    request (req, token) {
      this.options.http._setHeaders.call(this, req, {Authorization: 'Bearer ' + token});
    },

    response (res) {
      const {access_token, refresh_token, expires_in} = res.data;
      if (res.data && access_token && refresh_token && expires_in) { /*get tokens if none present then*/
        let expires_inDate = new Date();
        /*get exact time of expiration token*/
        expires_inDate.setSeconds(expires_inDate.getSeconds() + expires_in)
        localStorage.setItem('expires_in', expires_inDate)
        localStorage.setItem('refresh_token', refresh_token)
        return access_token;
      }
    }
  },
  router
})
```

You already defined this part inside VueAuth settings
Above that not sure this would be the best approach
```js
if(isExpired){
                Vue.auth.options.refreshData.data = querystring.stringify({
                    refresh_token: getRefreshToken()
                });
            }
```
of verifying whether the token is expired. It should be enough to compare the date.

Also can you show me the login method?

**Comment by mvatansever** [comment] 2017-09-19 10:12
Thank you but resolved the problem. The problem is here:
```
        this.$auth.login({
          body: {
            email: this.model.email,
            password: this.model.password
          }
        })
```

This is must be like this:

        this.$auth.login({
          data: {
            email: this.model.email,
            password: this.model.password
          }
        })

Thanks again for your support! Really appreciate!

**Comment by alexandru-paduraru** [comment] 2017-09-19 14:15
@cristijora great explanation. I was thinking if we should add this in the documentation, in case there are other persons who want to do this. And also all the things that we sent to people about Laravel. In this way we have something prepared to send very fast to the users. What do you think?

**Comment by cristijora** [comment] 2017-09-19 14:36
@alexandru-paduraru The authentication part, yes. I can add it since I know it pretty well. 
However, it's a bit debatable because you get into the field of integrating with an api and most of the time the authorization layer is different from api to api and the code samples might not be suited for all cases.

Regarding Laravel part, would be glad to add it but we don't have a very clear setup yet. Hopefully 2 @Failcookie from #14 will let us know of his progress so we have a more realistic vision there.

**Comment by Failcookie** [comment] 2017-10-05 01:01
Following up on this - If you are a Laravel user, here is a GREAT repo to reference and mimic. I've been using this myself. https://github.com/cretueusebiu/laravel-vue-spa

**Comment by kwatog** [comment] 2018-08-07 02:35
thanks @cristijora for this. very helpful. I managed to make this work with JWT with minimal changes. well, I'd like to say except the following:
1. Encapsulating everything into a plugin. there must be something wrong with how I defined the Plugin.
2. #auth.ready always return true even with cleared cookies and storage (raised an [issue] (https://github.com/websanova/vue-auth/issues/410) in vue-auth).

Here's my code
```

import servicePlugin from './services/servicePlugin'
Vue.use(servicePlugin)

locale.use(lang)

// configure router
const router = new VueRouter({
  routes, // short for routes: routes
  linkActiveClass: 'active'
})

Vue.router = router

let _this = this
Vue.use(VueAuth, {
  parseUserData (data) {
    return data;
  },    
  auth: {
    request (req, token) {
        this.options.http._setHeaders.call(this, req, {Authorization: 'JWT ' + token})
    },
    response (res) {
        const token = res.data.token
        let decoded = {}
        if (token) {
          decoded = JwtDecode(token)
        }
        if (Object.keys(decoded).length > 0) { /*get tokens if none present then*/
          const access_token = res.data.token
          const exp = decoded.exp
          const orig_iat = decoded.orig_iat
          console.log('decoded' + JSON.stringify(decoded))

          let expires_inDate = new Date();
          /*get exact time of expiration token*/
          expires_inDate.setSeconds(expires_inDate.getSeconds() + exp)

          localStorage.setItem('expires_in', expires_inDate)
          localStorage.setItem('access_token', access_token)
          localStorage.setItem('orig_iat', orig_iat)
          return access_token;
        }
    }
  },
  http: HttpDriver,
  router: VueRouterDriver,
  http: HttpDriver,
  tokenStore: ['cookie', 'localStorage'],
  authRedirect: {path: '/login'},
  loginData: {
      headers: {
          'Content-Type': 'application/json',
      },
      url: 'api-token-auth/',
      redirect: '/', 
      fetchUser: false
  },
  fetchData: {
    url: 'user/data/', 
    method: 'GET', 
    enabled: false
  },
  /*Default refresh request data and redirect.*/
  refreshData: {
      /*send refresh token before expiring to renew tokens*/
      url: 'api-token-refresh/',
      method: 'POST',
      enabled: true,
      interval: 30, /*0=no auto refresh*/
      data: {
        token: localStorage.getItem('access_token'),
        orig_iat: localStorage.getItem('orig_iat')
      },
      /*Problem: requests new refresh token without checking the expiration date*/
      fetchUser: false,
  },
  tokenExpired() {
      const expires_in = localStorage.getItem('expires_in')
      const now = new Date();
      const isExpired = expires_in && new Date(expires_in) < now
      const atoken = localStorage.getItem('access_token')
      if(isExpired){
          Vue.auth.options.refreshData.data = {token: atoken}
      }
      return isExpired
  },
  tokenDefaultName: 'access_token'    
})

```
I'm posting the code for those who are also using JWT and of course, hopefully someone can help with my issue.

**Comment by cristijora** [comment] 2018-08-12 13:32
@kwatog I'd love to help but this is slightly out of scope for the dashboard template. Please use stackoverflow, or official vue chat https://discordapp.com/invite/HBherRA or the repo for vue auth.

**Comment by cristijora** [comment] 2018-08-12 14:56
Added some basic information in the documentation for v2 [here](https://demos.creative-tim.com/vue-paper-dashboard-pro/documentation/general-tips.html#custom-components)

**Closed by cristijora** 2018-08-12 14:56 UTC
Labels: documentation update, question
